/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kelompok_2;

/**
 *
 * @author NIA
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class tabel_pembeli extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    

    /**
     * Creates new form tabel_pembeli
     */
    public tabel_pembeli() {
        initComponents();
        koneksidatabase DB = new koneksidatabase();
        DB.koneksi();
        con = DB.cn;
        stat = DB.st;
        tampil();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        vid_pembeli = new javax.swing.JTextField();
        vnama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        bedit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("nama pembeli");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 80, 90, 14);

        jLabel2.setText("id pembeli");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 40, 70, 14);

        bsimpan.setText("simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan);
        bsimpan.setBounds(57, 118, 80, 23);

        bhapus.setText("hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus);
        bhapus.setBounds(160, 120, 80, 23);
        getContentPane().add(vid_pembeli);
        vid_pembeli.setBounds(230, 30, 100, 30);
        getContentPane().add(vnama);
        vnama.setBounds(230, 70, 100, 30);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 160, 260, 100);

        bedit.setText("edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit);
        bedit.setBounds(260, 120, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        try {
            sql = "INSERT INTO pembeli VALUES ('"+vid_pembeli.getText()+"','"+vnama.getText()+"')";
            stat.execute(sql);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        try {
            sql = "update pembeli set nama = '"+vnama.getText()+"',jenis_tiket = '"+vjenis_tiket.getSelectedItem().toString()+"',jumlah = '"+vjumlah_tiket.getText()+"' where id_pembeli = '"+vid_pembeli.getText()+"'";
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil diedit");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        try {
            sql = "update pembeli set nama = '"+vnama.getText()+"',jenis_tiket = '"+vjenis_tiket.getSelectedItem().toString()+"',jumlah = '"+vjumlah_tiket.getText()+"' where id_pembel = '"+vid_pembeli.getText()+"'";
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil diedit");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_beditActionPerformed
    public void tampil(){
        int n = 0;
        DefaultTableModel tableModel;
        tabel.setToolTipText("");
        Object [] row = {"ID","NAMA"};
        tableModel = new DefaultTableModel(null,row);
        tabel.setModel(tableModel);
        try {
            sql= "select * from pembeli";
            rs = stat.executeQuery(sql);
            while (rs.next()){
                n = n+1;
                String id=rs.getString(1);
                String nama=rs.getString(2);
                String data[]={id,nama};
                tableModel.addRow(data);
            }
        } catch (Exception e) {
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabel_pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabel_pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabel_pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabel_pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tabel_pembeli().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField vid_pembeli;
    private javax.swing.JTextField vnama;
    // End of variables declaration//GEN-END:variables
}
